name: Kick off build
on:
  schedule:
    # Midnight daily
    - cron: "10 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Trigger build
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        id: checkout
        with:
          ref: dailybuild
      - name: Commit empty to trigger build
        env:
          BRANCH: dailybuild
        run: |
          date=$(date +"%Y.%m.%d")
          git config --global user.name bkreider
          git config --global user.email "bkreider@users.noreply.github.com"

          # Need an actual edit or PBS won't build recipe
          echo -ne "\n#" >> recipe/meta.yaml
          git commit -m "Build: $date" recipe/meta.yaml
          #git commit -m "Build: $date" --allow-empty recipe/meta.yaml
          git push origin "$BRANCH"
